---
title: "Einsatz von Bilderkennung mittels neuronalen Netzwerken in der Fischzucht der BAW in Kreuzstein"
author:
  - Anna Dünser^[Bundesamt für Wasserwirtschaft, anna.duenser@baw.at]
  - Hannes Oberreiter^[Institut der Biologie, Universität Graz, hoberreiter@gmail.com]
date: "`r Sys.Date()`"
output: pdf_document
bibliography: "references.bib"
link-citations: yes
---

# Einführung

Blutzellen Fische
- Warum
- Präparieren
- Auszählen

# Neuronales Netz YOLOv5

Das beschriebene händische Auszählen von Blutzellen ist sehr Zeitintensiv und auch individuell Fehleranfällig. Dadurch das automatische optische Bilderkennungen heutzutage breit zugänglich sind und immer bessere Leistung erbringen, war die Idee eine automatische segmentierte Bilderkennung für diesen Schritt einzusetzen. Für diese Bilderkennungen werden hauptsächlich neuronale Netzwerke eingesetzt und der YOLO-Architektur ist einer davon. YOLO steht hierbei für ein Akronym "You only look once" in Deutsch "Du schaust nur einmal". Dem Algorithmus zugrunde liegt ein sogenanntes Convolutional Neural Network (CNN) und dieses findet bereits breite Anwendungsgebiete auch in der Landwirtschaft. Es gibt mehrere Architekturen die neuronale Netzwerke zur Bilderkennung benutzen wie R-CNN (Region-based Convolutional
Networks) oder R-FCN (Region based Fully Convolutional Networks) die je Anwendung verschiedene Stärken haben. Die meisten dieser Architekturen können mittlerweile mit relativ wenig Aufwand als Benutzer in TensorFlow, eine OpenSource Platform für maschinelles Lernen von Google, erstellt und bereitgestellt werden.


Die YOLO-Architektur wurde im Jahr 2015 veröffentlicht [@yolo]. Dabei zerlegt ein Algorithmus jedes Bild in ein Grid-System und jede Zelle im Grid ist für sich selbst verantwortlich um die Objekte zu erkennen. Diese Methode zeichnet sich besonders durch Schnelligkeit in der Erkennung und im Training aus, hat aber Schwierigkeiten mit sehr kleinen Objekten. Mit jeder neuen Version wurde aber an den Handicaps geschraubt und YOLO liefert mittlerweile eine sehr gute Genauigkeit und seit Version 2 handelt es sich um ein fully convolutional netwerk (FCN) [@nakahara2018]. In unserem Fall wurde YOLOv5 verwendet [@yolov5], was bereits trainierte Modelle zur Verfügung stellt, sehr gute Dokumentation und eine einfache Funktionalität. Aufgebaut auf den PyTorch Framework [@pytorch] in Python, erlaubt es auch Personen mit nur rudimentären Kenntnissen in Programmieren bereits einfache Modelle zu erstellen und damit zu arbeiten.

# Methodik und Resultate

Für unseren Fall haben wir X Bilder zuerst annotiert und diese im Training auf HARDWARE mit vortrainierten Gewichten YOLO Large trainiert. Validation, also die Kontrolle wie gut die Daten sind wurde mit X Bildern durchgeführt. Was zu einer Erfolgrate von führte. Unser Projekt und die Trainingsdaten sind Open Source unter folgenden Link zu finden [GitHub](https://github.com/HannesOberreiter/baw-fish-cell-yolo).



# Referenzen

